### ISSUE TITLE
code+dependency verification failed on one command

### ISSUE THREAD

**Issue by hamid13r** [bpowell122/tomodrgn#3]
Hi,

I am trying to install tomodrgn, we are using micromamba and everything runs properly except one of the commands:

```
Command 21/33: tomodrgn convergence_vae output/06_vae_both_sim 49 --Apix 13.1 --random-seed 42 --final-maxima 2 --ground-truth data/10076_class*_32.mrc
Error returncode: 1
Traceback (most recent call last):
  File "/home/janlevinson/micromamba/envs/tomodrgn/bin/tomodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/janlevinson/micromamba/envs/tomodrgn/lib/python3.7/site-packages/tomodrgn/__main__.py", line 51, in main
    args.func(args)
  File "/home/janlevinson/micromamba/envs/tomodrgn/lib/python3.7/site-packages/tomodrgn/commands/convergence_vae.py", line 984, in main
    calculate_FSCs(outdir, epochs, labels, img_size, chimerax_colors, LOG)
  File "/home/janlevinson/micromamba/envs/tomodrgn/lib/python3.7/site-packages/tomodrgn/commands/convergence_vae.py", line 699, in calculate_FSCs
    x, fsc_masked[cluster, i, :] = utils.calc_fsc(vol1_path, vol2_path, mask='none')
ValueError: could not broadcast input array from shape (17,) into shape (16,)
```

I would appreciate any inputs. I do need to look further into the paper but wanted to see if this error is a major problem or fixable.

**Comment by GYGyk2000** [comment]
I have the same issue! I am using python 3.10 and cuda 11.8. I can pass all other tests.

**Comment by TimYi** [comment]
Same to me.
