### ISSUE TITLE
Analyze VAE: Error loading state_dict for TiltSeriesHetOnlyVAE

### ISSUE THREAD

**Issue by shahpnmlab** [bpowell122/tomodrgn#8]
**Describe the bug**
Following 100 epochs of training the vae, i now would like to analyse the results. However, the program crashes with the following error message

```
tomodrgn analyze 02_train_vae --epoch 99   --ksample 25 --device 0
2024-12-14 15:42:06     Namespace(workdir='/home/pranav/Desktop/pranav/data/training/nsp2/20240914_1_NSP2_6_NSP5_AuFid_pnms_stuart/tomodrgn/02_train_vae', epoch='99', device=0, outdir=None, skip_vol=False, skip_umap=False, plot_format='pn
g', pc=2, pc_ondata=False, ksample=25, downsample=None, lowpass=None, flip=False, invert=False, func=<function main at 0x7f55048e96c0>)
2024-12-14 15:42:06     Saving results to /home/pranav/Desktop/pranav/data/training/nsp2/20240914_1_NSP2_6_NSP5_AuFid_pnms_stuart/tomodrgn/02_train_vae/analyze.99
2024-12-14 15:42:06     Use cuda True
Traceback (most recent call last):
  File "/home/pranav/Desktop/pranav/software/miniconda3/envs/tomodrgn/bin/tomodrgn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pranav/Desktop/pranav/software/tomodrgn/tomodrgn/__main__.py", line 35, in main
    args.func(args)
  File "/home/pranav/Desktop/pranav/software/tomodrgn/tomodrgn/commands/analyze.py", line 522, in main
    vg = models.VolumeGenerator(config=config,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pranav/Desktop/pranav/software/tomodrgn/tomodrgn/models.py", line 869, in __init__
    model, lat = TiltSeriesHetOnlyVAE.load(config=cfg,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pranav/Desktop/pranav/software/tomodrgn/tomodrgn/models.py", line 136, in load
    model.load_state_dict(ckpt['model_state_dict'])
  File "/home/pranav/Desktop/pranav/software/miniconda3/envs/tomodrgn/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TiltSeriesHetOnlyVAE:
        Missing key(s) in state_dict: "encoder.encoder_a.main.0.weight", "encoder.encoder_a.main.0.bias", "encoder.encoder_a.main.2.linear.weight", "encoder.encoder_a.main.2.linear.bias", "encoder.encoder_a.main.4.linear.weight", "encoder.encoder_a.main.4.linear.bias", "encoder.encoder_a.main.6.linear.weight", "encoder.encoder_a.main.6.linear.bias", "encoder.encoder_a.main.8.weight", "encoder.encoder_a.main.8.bias", "encoder.encoder_b.main.0.weight", "encoder.encoder_b.main.0.bias", "encoder.encoder_b.main.2.linear.weight", "encoder.encoder_b.main.2.linear.bias", "encoder.encoder_b.main.4.linear.weight", "encoder.encoder_b.main.4.linear.bias", "encoder.encoder_b.main.6.linear.weight", "encoder.encoder_b.main.6.linear.bias", "encoder.encoder_b.main.8.linear.weight", "encoder.encoder_b.main.8.linear.bias", "decoder.freqs", "decoder.decoder.main.0.weight", "decoder.decoder.main.0.bias", "decoder.decoder.main.2.linear.weight", "decoder.decoder.main.2.linear.bias", "decoder.decoder.main.4.linear.weight", "decoder.decoder.main.4.linear.bias", "decoder.decoder.main.6.linear.weight", "decoder.decoder.main.6.linear.bias", "decoder.decoder.main.8.weight", "decoder.decoder.main.8.bias".
        Unexpected key(s) in state_dict: "module.encoder.encoder_a.main.0.weight", "module.encoder.encoder_a.main.0.bias", "module.encoder.encoder_a.main.2.linear.weight", "module.encoder.encoder_a.main.2.linear.bias", "module.encoder.encoder_a.main.4.linear.weight", "module.encoder.encoder_a.main.4.linear.bias", "module.encoder.encoder_a.main.6.linear.weight", "module.encoder.encoder_a.main.6.linear.bias", "module.encoder.encoder_a.main.8.weight", "module.encoder.encoder_a.main.8.bias", "module.encoder.encoder_b.main.0.weight", "module.encoder.encoder_b.main.0.bias", "module.encoder.encoder_b.main.2.linear.weight", "module.encoder.encoder_b.main.2.linear.bias", "module.encoder.encoder_b.main.4.linear.weight", "module.encoder.encoder_b.main.4.linear.bias", "module.encoder.encoder_b.main.6.linear.weight", "module.encoder.encoder_b.main.6.linear.bias", "module.encoder.encoder_b.main.8.linear.weight", "module.encoder.encoder_b.main.8.linear.bias", "module.decoder.freqs", "module.decoder.decoder.main.0.weight", "module.decoder.decoder.main.0.bias", "module.decoder.decoder.main.2.linear.weight", "module.decoder.decoder.main.2.linear.bias", "module.decoder.decoder.main.4.linear.weight", "module.decoder.decoder.main.4.linear.bias", "module.decoder.decoder.main.6.linear.weight", "module.decoder.decoder.main.6.linear.bias", "module.decoder.decoder.main.8.weight", "module.decoder.decoder.main.8.bias".
(tomodrgn) scanubuntu:
```
my command for training the network is
```
#tomodrgn train_vae j18_r3d_particles_optimisation_set.star \
#    --datadir particleseries/ \
#    --outdir 02_train_vae/ \
#    --source-software warptools \
#    --uninvert-data \
#    --lazy \
#    --enc-dim-A 256 \
#    --enc-layers-A 3 \
#    --out-dim-A 128 \
#    --enc-dim-B 256 \
#    --enc-layers-B 3 \
#    --zdim 128 \
#    --dec-dim 256 \
#    --dec-layers 3 \
#    -n 100 \
#    -b 51 \
#    --l-dose-mask \
#    --recon-dose-weight \
#    --recon-tilt-weight \
#    --multigpu \
#    --pin-memory
```

**Comment by bpowell122** [comment]
@shahpnmlab Thank you for the detailed bug report! Apologies for my delayed reply, I was traveling without internet over the winter holidays. I was able to reproduce your reported issue, and implemented a fix in #9 . 

The fix prevents this problem from occurring in newly trained models, but doesn't itself address models trained with the old code. If you want to use your old model, you just need to update the key names in the weights.pkl file that you'd like to analyze:
```
from collections import OrderedDict
import torch
weights_path = 'weights.99.pkl'
ckpt = torch.load(weights_path, weights_only=True)
ckpt['model_state_dict'] = OrderedDict((k.replace('module.', ''), v) for k, v in ckpt['model_state_dict'].items())
torch.save(ckpt, weights_path)
```

You should then be able to run `tomodrgn analyze 02_train_vae --epoch 99  --ksample 25 --device 0` without error. 

As an aside, I noticed you're using batch size 51 for model training. Datasets that I have processed have typically shown quite noisy loss curves with --batch-size above 16(ish). That does not seem to degrade the quality of the reconstructed volumes as far as I can tell, but I usually feel more comfortable with a more canonically smooth loss curve during training. I have some comments on this point here: https://bpowell122.github.io/tomodrgn/tutorials/learn_structural_heterogeneity.html#common-pitfalls

**Comment by shahpnmlab** [comment]
Hi @bpowell122, Thanks for the fix. That batch size was a typo, I meant to be using an even larger value of 512 😆  (since I have 48GB cards to play with!). I will go with the suggested batch size once I have updated the program rerun training. Meanwhile, with the previous version, I was seeing this artefact with volumes that were being reconstructed. Could this be because of the batch size issue?

![Image](https://github.com/user-attachments/assets/501e9814-e330-4c49-a7c5-259083f2c273)

**Comment by bpowell122** [comment]
Ah good for you with those GPUs! But yes, I would recommend decreasing the batch size substantially when you retrain the model. For the datasets I've processed, I've never gone above ~64, and usually find much lower batch sizes of 1-16 tend to be more stable. The large batch size could be causing the artifacts you're seeing (possibly along with the model being overfit after training 100 epochs, as one sign of overfitting is the appearance of strong high frequency components). 

If needed for processing a trained model, you can also apply a lowpass filter to all generated volumes using ``tomodrgn analyze .... --lowpass X`` or ``tomodrgn eval_vol ... --lowpass X``, but I would try improving model training first (lower batch size and avoiding overfitting).

Model inference (``tomodrgn eval_vol ... --batch-size B``, where B can be as large as your card supports) is where you'll be better able to take advantage of those cards for parallelized volume generation.
